version: '3'
services:
  service-a:
    build:
      context: ./service-a
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  service-b:
    build:
      context: ./service-b
      dockerfile: Dockerfile
    ports:
      - "8082:8082"

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - service.a.url=http://service-a:8081/
      - service.b.url=http://service-b:8082/
